all: 1 2 3 4 5 6

1:
	cp /share/isilon/system/local/NGSTestSets/Illumina_HiSeq/paired_end/mixed_strand/RNAseq/1/OM/S17_L1_1.fq.gz rna1/

2:
	cp /share/isilon/system/local/NGSTestSets/Illumina_HiSeq/paired_end/mixed_strand/RNAseq/1/OM/S17_L1_2.fq.gz rna1/

3:
	cp /share/isilon/system/local/NGSTestSets/Illumina_HiSeq/paired_end/mixed_strand/RNAseq/1/OM/S27_L1_1.fq.gz rna1/

4:
	cp /share/isilon/system/local/NGSTestSets/Illumina_HiSeq/paired_end/mixed_strand/RNAseq/1/OM/S27_L1_2.fq.gz rna1/

5:
	cp /share/isilon/system/local/NGSTestSets/Illumina_HiSeq/paired_end/mixed_strand/RNAseq/1/SC/S18_L1_1.fq.gz rna2/

6:
	cp /share/isilon/system/local/NGSTestSets/Illumina_HiSeq/paired_end/mixed_strand/RNAseq/1/SC/S18_L1_2.fq.gz rna2/
